env:
    - ARCH=x86
language: python
sudo: false
python:
    - "2.7"
cache:
  directories:
    - "$HOME/.pip-cache/"
    - "/home/travis/virtualenv/python2.7"
install: 
    - "pip install -r requirements.txt  --download-cache $HOME/.pip-cache"
    - "pip install python-coveralls --download-cache $HOME/.pip-cache"
    - "pip install coverage  --download-cache $HOME/.pip-cache"
    - "pip install flake8  --download-cache $HOME/.pip-cache"
before_script:
    - "flake8 jasper.py client tests"
script:
    - "coverage run -m unittest discover -p tests"
after_success:
    - "coverage report"
    - "coveralls"
